name: Integration tests

on:
  - push
  - pull_request

jobs:
  bdd:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:
          - "1.20"
    name: Integration tests for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: ./build.sh --test-rules-only
      - name: Run tests
        run: ./test.sh
